name: Wampproto Dart CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.4.0

      - name: Install dependencies
        run: make install

      - name: Verify formatting
        run: make check-format

      - name: Check lint
        run: make lint

      - name: Install wampproto-cli
        run: make install-wampproto

      - name: Run tests
        run: make tests
